name: Module Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Package
      run: |
        mkdir release
        cp LICENSE README.md Data/Dockerfile startup.sh release/
        zip -r release.zip release/

    - name: Upload Release Package
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: release.zip

    - name: Deploy
      run: |
        cp -R release deployment
        cd deployment
        docker build -t dockeryolo -f Data/Dockerfile .
        docker run -d \
          --name "dockerWorking" \
          -p 21:21 \
          -p 4470:4470 \
          -p 40000-40100:40000-40100 \
          dockeryolo

    - name: Test
      run: |
        cp -R scr_Box_test test
        cd test
        pip install pipenv
        pipenv install
        pipenv run pytest

