name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: --privileged
        ports:
          - 2375:2375

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up Docker environment
      run: |
        echo "DOCKER_HOST=tcp://localhost:2375" >> $GITHUB_ENV

    - name: Wait for Docker to be ready
      run: |
        for i in {1..30}; do
          docker info && break || sleep 10
        done

    - name: Build Docker image
      run: |
        cd Data
        docker build -t dockeryolo .

    - name: Run Docker container
      run: |
        docker run --name dockeryolo_container -d \
        -p 21:21 -p 4470:4470 -p 40000-40100:40000-40100 dockeryolo

    - name: Install Python and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3-pip -y
        pip3 install pytest docker

    - name: Run tests
      run: |
        cd Data
        pytest test_docker_env.py

    - name: Cleanup
      run: |
        docker stop dockeryolo_container
        docker rm dockeryolo_container
